#Data
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[15]}]


set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vid_data[23]}]

#Sync signals
set_property IOSTANDARD LVCMOS33 [get_ports vid_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vid_vsync]

set_property PACKAGE_PIN M11 [get_ports {vid_data[23]}]
set_property PACKAGE_PIN M10 [get_ports {vid_data[22]}]
set_property PACKAGE_PIN N9 [get_ports {vid_data[21]}]
set_property PACKAGE_PIN M9 [get_ports {vid_data[20]}]
set_property PACKAGE_PIN N14 [get_ports {vid_data[19]}]
set_property PACKAGE_PIN N13 [get_ports {vid_data[18]}]
set_property PACKAGE_PIN L13 [get_ports {vid_data[17]}]
set_property PACKAGE_PIN K13 [get_ports {vid_data[16]}]
set_property PACKAGE_PIN N8 [get_ports {vid_data[15]}]
set_property PACKAGE_PIN P10 [get_ports {vid_data[14]}]
set_property PACKAGE_PIN R10 [get_ports {vid_data[13]}]
set_property PACKAGE_PIN N7 [get_ports {vid_data[12]}]
set_property PACKAGE_PIN N12 [get_ports {vid_data[11]}]
set_property PACKAGE_PIN N11 [get_ports {vid_data[10]}]
set_property PACKAGE_PIN P14 [get_ports {vid_data[9]}]
set_property PACKAGE_PIN P13 [get_ports {vid_data[8]}]
set_property PACKAGE_PIN R7 [get_ports {vid_data[7]}]
set_property PACKAGE_PIN P9 [get_ports {vid_data[6]}]
set_property PACKAGE_PIN P8 [get_ports {vid_data[5]}]
set_property PACKAGE_PIN R8 [get_ports {vid_data[4]}]
set_property PACKAGE_PIN M14 [get_ports {vid_data[3]}]
set_property PACKAGE_PIN L14 [get_ports {vid_data[2]}]
set_property PACKAGE_PIN M15 [get_ports {vid_data[1]}]
set_property PACKAGE_PIN L15 [get_ports {vid_data[0]}]
set_property PACKAGE_PIN P15 [get_ports vid_hsync]
set_property PACKAGE_PIN R15 [get_ports vid_vsync]
